name: build

on:
  push:
    branches:
    - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm i -g noop
      - run: npm ci
      - run: npm test
